[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "arm-unknown-linux-musleabihf" },
    { triple = "aarch64-unknown-linux-musl" },
]
all-features = true
no-default-features = false

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    { id = "RUSTSEC-2023-0071", reason = "we are only using RSA internally for testing" },
]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "MPL-2.0",
    "ISC",
    "0BSD",
    "Unicode-3.0",
    "CC0-1.0",
    "Zlib",
    "NCSA",
]
confidence-threshold = 0.96

[licenses.private]
ignore = false

[sources]
allow-git = [
    "git+https://github.com/silitics/sidex.git"
]

[bans]
multiple-versions = "allow"
